<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { fetchJob } from '@/api/jobs'
import { fetchJobMatch } from '@/api/match'
import { fetchProfile, isProfileNotFound } from '@/api/profile'
import { showError } from '@/api/http'
import { CONDITION_LABELS, matchStatus } from '@/utils/matchStatus'
import type { JobPosition, MatchResult } from '@/types/model'
const route=useRoute();const router=useRouter();const id=Number(route.params.id);const job=ref<JobPosition>();const match=ref<MatchResult>();const loading=ref(true)
const info=computed(()=>job.value?[['招录单位',job.value.departmentName],['用人单位',job.value.organizationName],['岗位名称',job.value.positionName],['岗位代码',job.value.positionCode],['地区',[job.value.province,job.value.city,job.value.district].filter(Boolean).join(' ')],['招录人数',job.value.recruitCount ? `${job.value.recruitCount} 人` : null],['学历',job.value.educationRequirement],['学位',job.value.degreeRequirement],['专业',job.value.majorRequirement],['年龄',job.value.ageRequirement],['政治面貌',job.value.politicalRequirement],['基层工作经历',job.value.workYearRequirement],['应届要求',job.value.freshGraduateRequirement],['户籍',job.value.householdRequirement],['资格证书',job.value.certificateRequirement],['职位描述',job.value.positionDescription],['备注',job.value.remark]]:[])
onMounted(async()=>{try{const profile=await fetchProfile();if (!profile) return;[job.value,match.value]=await Promise.all([fetchJob(id),fetchJobMatch(id,profile.id)])}catch(error){if(isProfileNotFound(error))router.replace('/profile');else showError(error,'读取岗位详情失败。')}finally{loading.value=false}})
function evidenceText(item: MatchResult['items'][number]) { const e=item.evidence;if(!e)return '';const catalog=e.catalogName ? `判断依据：${e.catalogName}` : '';const relationship=e.majorName && e.parentName ? `${e.majorName}${e.majorCode ? `（${e.majorCode}）` : ''} 属于 ${e.parentName}${e.parentCode ? `（${e.parentCode}）` : ''}` : '';return [catalog,relationship].filter(Boolean).join('；') }
</script>
<template><section v-loading="loading"><div v-if="job" class="page-card"><div class="title-row"><div><h1 class="page-title">{{ job.positionName || '岗位详情' }}</h1><p class="page-subtitle">{{ job.departmentName || '-' }} · 岗位代码：{{ job.positionCode || '-' }}</p></div><el-tag v-if="match" size="large" :type="matchStatus(match.result).type">{{ matchStatus(match.result).label }}</el-tag></div><el-descriptions :column="2" border><el-descriptions-item v-for="[label,value] in info" :key="label ?? ''" :label="label ?? ''"><span class="description-value">{{ value || '-' }}</span></el-descriptions-item></el-descriptions></div><div v-if="match" class="page-card match-panel"><h2 class="page-title">为什么我{{ match.result === 'MATCH' ? '能报' : match.result === 'NOT_MATCH' ? '不能报' : '需要确认' }}</h2><p class="page-subtitle">综合判断：<el-tag :type="matchStatus(match.result).type">{{ matchStatus(match.result).detailLabel }}</el-tag></p><div v-for="item in match.items" :key="item.conditionType" class="match-item"><div class="item-title"><strong>{{ CONDITION_LABELS[item.conditionType] || item.conditionType }}</strong><el-tag :type="matchStatus(item.result).type">{{ matchStatus(item.result).detailLabel }}</el-tag></div><p>你的条件：{{ item.userValue || '未填写' }}</p><p>岗位要求：{{ item.requirementValue || '未明确' }}</p><p>原因：{{ item.reason || '暂无说明' }}</p><p v-if="evidenceText(item)" class="evidence">{{ evidenceText(item) }}</p></div></div></section></template>
<style scoped>.title-row{display:flex;align-items:start;justify-content:space-between}.description-value{white-space:pre-wrap;line-height:1.6}.match-panel{margin-top:20px}.match-item{padding:18px 0;border-bottom:1px solid #ebeef5}.match-item:last-child{border-bottom:0}.item-title{display:flex;align-items:center;gap:10px}.match-item p{margin:8px 0 0;color:#606266}.evidence{color:#409eff!important}</style>
