<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { confirmImport, fetchMapping } from '@/api/import'
import { showError } from '@/api/http'
import { STANDARD_FIELDS } from '@/utils/fields'
import type { FieldMappingPreview, ImportResult, MappingItem } from '@/types/model'
const route = useRoute(); const router = useRouter(); const importId = Number(route.params.id); const data = ref<FieldMappingPreview | null>(null); const mappings = ref<MappingItem[]>([]); const result = ref<ImportResult | null>(null); const loading = ref(false)
const mappedNames = computed(() => new Set(mappings.value.map(item => item.targetField).filter(Boolean)))
onMounted(async () => { try { data.value = await fetchMapping(importId); mappings.value = data.value.headers.map(item => ({ sourceField: item.sourceField, targetField: item.suggestedField })) } catch (error) { showError(error, '读取字段映射失败。') } })
function optionsFor(item: MappingItem) { return STANDARD_FIELDS.filter(([key]) => key === item.targetField || !mappedNames.value.has(key)) }
async function submit() { if (!mappings.value.some(item => item.targetField === 'positionName')) { ElMessage.warning('岗位名称是关键字段，请至少映射“岗位名称”。'); return } loading.value = true; try { result.value = await confirmImport(importId, mappings.value); ElMessage.success('岗位导入完成。') } catch (error) { showError(error, '职位表导入失败。') } finally { loading.value = false } }
</script>
<template><section class="page-card"><h1 class="page-title">确认字段映射</h1><p class="page-subtitle">Sheet：{{ data?.sheetName ?? '-' }}。可修改系统建议；“岗位名称”为关键字段。</p><el-table v-if="data" :data="data.headers" border><el-table-column type="index" width="58" label="#" /><el-table-column label="Excel 原始字段" min-width="260"><template #default="{ row }"><span>{{ row.sourceField }}</span><el-tag v-if="row.sourceField === '招考职位' || mappings.find(item => item.sourceField === row.sourceField)?.targetField === 'positionName'" size="small" type="danger" effect="plain" class="key-tag">关键</el-tag></template></el-table-column><el-table-column label="识别状态" width="140"><template #default="{ row }"><el-tag :type="row.confidence === 'EXACT' ? 'success' : row.confidence === 'ALIAS' ? 'primary' : 'warning'">{{ row.confidence === 'EXACT' ? '精确识别' : row.confidence === 'ALIAS' ? '同义词识别' : '未识别' }}</el-tag></template></el-table-column><el-table-column label="系统标准字段" min-width="280"><template #default="{ $index }"><el-select v-model="mappings[$index].targetField" clearable placeholder="不导入该字段"><el-option label="不导入该字段" value="" /><el-option v-for="[key, label] in optionsFor(mappings[$index])" :key="key" :label="label" :value="key" /></el-select></template></el-table-column></el-table><div v-if="!result" class="actions"><el-button type="primary" :loading="loading" @click="submit">确认导入职位</el-button></div><div v-if="result" class="result"><el-result icon="success" title="职位导入完成" :sub-title="`共 ${result.totalRows} 行，成功 ${result.successRows} 行，失败 ${result.failedRows} 行`"><template #extra><el-button type="primary" @click="router.push(`/import/${importId}/execute`)">开始智能匹配</el-button></template></el-result><el-table v-if="result.failedItems.length" :data="result.failedItems" border><el-table-column prop="row" label="失败行号" width="140" /><el-table-column prop="reason" label="失败原因" /></el-table></div></section></template>
<style scoped>.key-tag{margin-left:8px}.actions{margin-top:22px;text-align:right}.result{margin-top:18px}</style>
