<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { createProfile, fetchProfile, isProfileNotFound, updateProfile } from '@/api/profile'
import { showError } from '@/api/http'
import type { ProfileForm } from '@/types/model'

type FormInstance = { validate: () => Promise<boolean> }
type FormRules = Record<string, unknown>
const formRef = ref<FormInstance>()
const exists = ref(false)
const loading = ref(false)
const form = reactive<ProfileForm>({ name: null, gender: null, birthDate: null, politicalStatus: null, education: null, degree: null, major: null, majorCode: null, graduationDate: null, workYears: null, freshGraduateStatus: null, household: null, studentOrigin: null, serviceProjectType: null, veteran: null, certificates: null, targetRegion: null, notes: null })
const rules: FormRules = { birthDate: [{ required: true, message: '请选择出生日期', trigger: 'change' }], education: [{ required: true, message: '请选择学历', trigger: 'change' }], major: [{ required: true, message: '请填写专业', trigger: 'blur' }], politicalStatus: [{ required: true, message: '请选择政治面貌', trigger: 'change' }], workYears: [{ required: true, message: '请填写基层工作年限', trigger: 'blur' }] }
onMounted(async () => { try { Object.assign(form, await fetchProfile()); exists.value = true } catch (error) { if (!isProfileNotFound(error)) showError(error, '读取档案失败。') } })
async function save() { if (!formRef.value || !(await formRef.value.validate().catch(() => false))) return; loading.value = true; try { const saved = exists.value ? await updateProfile(form) : await createProfile(form); Object.assign(form, saved); exists.value = true; ElMessage.success('报考档案已保存。') } catch (error) { showError(error, '保存档案失败。') } finally { loading.value = false } }
</script>

<template><section class="page-card"><h1 class="page-title">我的报考档案</h1><p class="page-subtitle">请如实填写个人条件，匹配结果仅供报考前核验参考。</p><el-form ref="formRef" :model="form" :rules="rules" label-width="112px" class="profile-form"><el-row :gutter="28"><el-col :span="12"><el-form-item label="姓名"><el-input v-model="form.name" placeholder="选填" /></el-form-item><el-form-item label="出生日期" prop="birthDate"><el-date-picker v-model="form.birthDate" value-format="YYYY-MM-DD" type="date" placeholder="选择日期" /></el-form-item><el-form-item label="学历" prop="education"><el-select v-model="form.education" placeholder="请选择"><el-option v-for="item in ['高中','专科','本科','硕士','博士']" :key="item" :label="item" :value="item" /></el-select></el-form-item><el-form-item label="学位"><el-input v-model="form.degree" placeholder="如：学士、硕士" /></el-form-item><el-form-item label="专业" prop="major"><el-input v-model="form.major" /></el-form-item><el-form-item label="专业代码"><el-input v-model="form.majorCode" placeholder="如：080902" /></el-form-item><el-form-item label="政治面貌" prop="politicalStatus"><el-select v-model="form.politicalStatus" placeholder="请选择"><el-option v-for="item in ['中共党员','中共预备党员','共青团员','群众','民主党派','其他']" :key="item" :label="item" :value="item" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="基层工作年限" prop="workYears"><el-input-number v-model="form.workYears" :min="0" :max="50" /></el-form-item><el-form-item label="应届身份"><el-select v-model="form.freshGraduateStatus" clearable placeholder="请选择"><el-option label="是" value="是" /><el-option label="否" value="否" /></el-select></el-form-item><el-form-item label="户籍"><el-input v-model="form.household" /></el-form-item><el-form-item label="生源地"><el-input v-model="form.studentOrigin" /></el-form-item><el-form-item label="服务基层项目"><el-input v-model="form.serviceProjectType" /></el-form-item><el-form-item label="退役军人"><el-select v-model="form.veteran" clearable placeholder="请选择"><el-option label="是" value="是" /><el-option label="否" value="否" /></el-select></el-form-item><el-form-item label="资格证书"><el-input v-model="form.certificates" /></el-form-item></el-col></el-row><el-form-item label="备注"><el-input v-model="form.notes" type="textarea" :rows="3" /></el-form-item><el-form-item><el-button type="primary" :loading="loading" @click="save">保存档案</el-button></el-form-item></el-form></section></template>
<style scoped>.profile-form { max-width: 950px; margin-top: 28px; }.el-select,.el-date-editor { width: 100%; }</style>
