<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { ElMessageBox } from 'element-plus/es/components/message-box/index.mjs'
import { deleteRecruitmentNotices, discoverRecruitment, fetchRecruitmentNotices, updateRecruitmentStatus } from '@/api/recruitment'
import { showError } from '@/api/http'
import type { RecruitmentNotice, RecruitmentNoticeStatus } from '@/types/model'
type NoticeFilterStatus=RecruitmentNoticeStatus|'UNREAD'
const router=useRouter(),status=ref<NoticeFilterStatus|''>(''),keyword=ref(''),items=ref<RecruitmentNotice[]>([]),selectedIds=ref<number[]>([]),total=ref(0),page=ref(1),loading=ref(false),pulling=ref(false),deleting=ref(false)
const labels:Record<RecruitmentNoticeStatus,string>={NEW:'新发现',INTERESTED:'感兴趣',FOLLOWING:'正在看',IGNORED:'已忽略'}
onMounted(load)
async function load(){loading.value=true;selectedIds.value=[];try{const data=await fetchRecruitmentNotices({status:status.value||undefined,keyword:keyword.value||undefined,page:page.value,pageSize:20});items.value=data.items;total.value=data.total}catch(e){showError(e,'读取招聘公告失败。')}finally{loading.value=false}}
async function pull(){pulling.value=true;try{const r=await discoverRecruitment();if(r.failedCount>0){ElMessage.warning(`拉取完成，但有 ${r.failedCount} 个来源或公告处理失败；获取 ${r.fetchedCount} 条，新增 ${r.newCount} 条。`)}else{ElMessage.success(`拉取完成：获取 ${r.fetchedCount} 条，新增 ${r.newCount} 条，已存在 ${r.duplicateCount} 条`)}page.value=1;await load()}catch(e){showError(e,'拉取招聘信息失败。')}finally{pulling.value=false}}
async function setStatus(n:RecruitmentNotice,s:RecruitmentNoticeStatus){try{await updateRecruitmentStatus(n.id,s);n.userStatus=s;ElMessage.success(`已标记为${labels[s]}`)}catch(e){showError(e,'更新公告状态失败。')}}
async function removeSelected(){if(!selectedIds.value.length)return;try{await ElMessageBox.confirm(`将永久删除 ${selectedIds.value.length} 篇公告，以及其已解析岗位、附件和匹配记录。此操作不可恢复。`,'确认删除',{confirmButtonText:'删除',cancelButtonText:'取消',type:'warning'});deleting.value=true;await deleteRecruitmentNotices(selectedIds.value);ElMessage.success('已删除所选公告');if(items.value.length===selectedIds.value.length&&page.value>1)page.value--;await load()}catch(e){if(e!=='cancel'&&e!=='close')showError(e,'删除公告失败。')}finally{deleting.value=false}}
function noticeLabel(n:RecruitmentNotice){return n.userStatus==='NEW'?(n.viewedAt?'已查阅':'未查阅'):labels[n.userStatus]}
function detail(n:RecruitmentNotice){router.push({name:'recruitment-notice-detail',params:{id:n.id}})}
function changeStatus(v:string|number){status.value=(v||'') as NoticeFilterStatus|'';page.value=1;load()}function search(){page.value=1;load()}function changePage(v:number){page.value=v;load()}
</script>
<template><section><div class="page-card head"><div><h1 class="page-title">招聘发现</h1><p class="page-subtitle">从公开招聘网站发现最新公告，集中管理你的关注状态。</p></div><el-button type="primary" :loading="pulling" @click="pull">立即拉取</el-button></div><div class="page-card toolbar"><el-tabs :model-value="status" @tab-change="changeStatus"><el-tab-pane label="全部" name=""/><el-tab-pane label="未查阅" name="UNREAD"/><el-tab-pane label="感兴趣" name="INTERESTED"/><el-tab-pane label="正在看" name="FOLLOWING"/><el-tab-pane label="已忽略" name="IGNORED"/></el-tabs><el-input v-model="keyword" clearable placeholder="搜索公告标题" @keyup.enter="search"><template #append><el-button @click="search">搜索</el-button></template></el-input></div><div v-loading="loading"><div v-if="items.length" class="batch-actions"><span>已选 {{ selectedIds.length }} 篇</span><el-button type="danger" plain :disabled="!selectedIds.length" :loading="deleting" @click="removeSelected">删除已选</el-button></div><el-empty v-if="!items.length&&!loading" description="暂无招聘公告，点击“立即拉取”开始发现。"/><article v-for="n in items" :key="n.id" class="page-card notice"><el-checkbox v-model="selectedIds" :label="n.id" :aria-label="`选择公告：${n.title}`"/><div class="notice-main"><h2>{{n.title}}</h2><p>{{n.sourceName}} · 发布时间：{{n.publishDate?.replace('T',' ')||'未知'}} · <span :class="{muted:n.viewedAt}">{{n.viewedAt?'已查看':'未查看'}}</span></p></div><div class="actions"><el-tag>{{noticeLabel(n)}}</el-tag><el-button @click="detail(n)">详情</el-button><el-button v-if="n.userStatus!=='INTERESTED'" @click="setStatus(n,'INTERESTED')">感兴趣</el-button></div></article><div v-if="total" class="pager"><el-pagination background layout="total,prev,pager,next" :total="total" :page-size="20" :current-page="page" @current-change="changePage"/></div></div></section></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.toolbar{display:flex;align-items:center;gap:24px;margin-bottom:16px}.toolbar .el-tabs{flex:1}.toolbar .el-input{width:300px}.batch-actions{display:flex;align-items:center;justify-content:space-between;margin:0 0 10px;padding:0 4px;color:#606266;font-size:14px}.notice{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.notice-main{min-width:0;flex:1}.notice h2{font-size:17px;margin:0 0 10px}.notice p{margin:0;color:#606266;font-size:13px}.actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;justify-content:flex-end}.muted{color:#909399}.pager{text-align:right;margin:22px 0}@media(max-width:768px){.toolbar{display:block}.toolbar .el-input{width:100%;margin-top:8px}.notice{align-items:flex-start}.actions{max-width:120px}.batch-actions{padding:0}}</style>
