<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { fetchProfile, isProfileNotFound } from '@/api/profile'
import { fetchMatchResults } from '@/api/match'
import { showError } from '@/api/http'
import { matchStatus } from '@/utils/matchStatus'
import type { MatchPositionResult, MatchResultValue } from '@/types/model'
const route=useRoute();const router=useRouter();const importId=Number(route.params.importId);const profileId=ref<number>();const total=ref(0);const items=ref<MatchPositionResult[]>([]);const page=ref(1);const size=10;const loading=ref(false);const current=ref<MatchResultValue>((route.query.result as MatchResultValue)||'MATCH')
async function load(){if(!profileId.value)return;loading.value=true;try{const data=await fetchMatchResults({profileId:profileId.value,importId,result:current.value,page:page.value,size});total.value=data.total;items.value=data.items}catch(error){showError(error,'读取匹配结果失败。')}finally{loading.value=false}}
onMounted(async()=>{try{const profile=await fetchProfile();if(!profile)return;profileId.value=profile.id;await load()}catch(error){if(isProfileNotFound(error))router.replace('/profile');else showError(error,'读取个人档案失败。')}})
watch(current,()=>{page.value=1;router.replace({query:{result:current.value}});load()})
function changePage(value:number){page.value=value;load()}
function openDetail(item:MatchPositionResult){router.push({path:`/jobs/${item.jobId}`,query:{importId:String(importId),result:current.value}})}
</script>
<template><section><div class="page-card result-head"><h1 class="page-title">岗位匹配结果</h1><p class="page-subtitle">默认优先展示明确可报岗位；请以招录单位最终审核为准。</p><el-radio-group v-model="current"><el-radio-button label="MATCH">可以报</el-radio-button><el-radio-button label="UNCERTAIN">待确认</el-radio-button><el-radio-button label="NOT_MATCH">不符合</el-radio-button></el-radio-group></div><div v-loading="loading" class="jobs"><el-empty v-if="!items.length&&!loading" :description="current==='MATCH'?'当前没有明确可报岗位，可以查看“待确认”岗位进一步核实。':'当前没有该状态的岗位。'"/><article v-for="item in items" :key="item.jobId" class="job-card"><div class="job-main"><el-tag :type="matchStatus(item.matchResult).type">{{matchStatus(item.matchResult).label}}</el-tag><h2>{{item.positionName||'未命名岗位'}}</h2><p>{{item.departmentName||'招录单位未填'}} <span v-if="item.organizationName">· {{item.organizationName}}</span></p><div class="job-meta"><span>岗位代码：{{item.positionCode||'-'}}</span><span>地区：{{[item.province,item.city].filter(Boolean).join(' ')||'-'}}</span><span>招录：{{item.recruitCount??'-'}}人</span><span>学历：{{item.educationRequirement||'-'}}</span><span>专业：{{item.majorRequirement||'-'}}</span></div></div><el-button type="primary" plain @click="openDetail(item)">查看详情</el-button></article><div class="pager" v-if="total"><el-pagination background layout="total, prev, pager, next" :total="total" :page-size="size" :current-page="page" @current-change="changePage"/></div></div></section></template>
<style scoped>.result-head{margin-bottom:18px}.jobs{min-height:260px}.job-card{background:#fff;border-radius:8px;padding:20px 22px;margin-bottom:14px;display:flex;align-items:center;justify-content:space-between;gap:20px;border:1px solid #ebeef5}.job-main{min-width:0}.job-main h2{font-size:17px;margin:10px 0 5px}.job-main p{margin:0 0 14px;color:#606266}.job-meta{display:flex;gap:20px;flex-wrap:wrap;font-size:13px;color:#606266}.pager{text-align:right;margin:24px 0}</style>
