package com.gk.jobhelper.controller;

import com.fasterxml.jackson.databind.*;import com.gk.jobhelper.entity.*;import com.gk.jobhelper.mapper.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.*;
import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class Iteration8ApiTest {
 @Autowired MockMvc mvc;@Autowired UserProfileMapper profiles;@Autowired ImportFileMapper imports;@Autowired JobPositionMapper positions;@Autowired JobMatchMapper matches;@Autowired JobFavoriteMapper favorites;@Autowired JobPositionFeatureMapper features;@Autowired JobInterviewScoreMapper scores;@Autowired JobPreferenceMapper preferences;ObjectMapper json=new ObjectMapper();Long profileId,importId,positionId;
 @BeforeEach void setup(){favorites.deleteAll();preferences.deleteAll();matches.deleteAllItems();matches.deleteAll();scores.deleteAll();features.deleteAll();positions.deleteAll();profiles.deleteAll();imports.deleteAll();UserProfile p=new UserProfile();p.setName("迭代8档案");p.setEducation("本科");p.setCreatedAt(LocalDateTime.now());profiles.insert(p);profileId=p.getId();ImportFile f=new ImportFile();f.setOriginalName("2026-jobs.xls");f.setStoredName("jobs.xls");f.setStoredPath("target/jobs.xls");f.setExamYear(2026);f.setStatus("IMPORTED");f.setCreatedAt(LocalDateTime.now());imports.insert(f);importId=f.getId();JobPosition job=new JobPosition();job.setImportFileId(importId);job.setPositionCode("A001");job.setPositionName("行政执法岗");job.setDepartmentName("南昌市某局");job.setProvince("江西");job.setCity("南昌");job.setRecruitCount(1);job.setMajorRequirement("不限");job.setRawData("{\"科目数量\":\"考两科\",\"考试科目\":\"行政职业能力测验,申论（行政执法类）\"}");job.setCreatedAt(LocalDateTime.now());job.setUpdatedAt(LocalDateTime.now());positions.insertBatch(Collections.singletonList(job));positionId=job.getId();JobMatch m=new JobMatch();m.setProfileId(profileId);m.setJobPositionId(positionId);m.setImportFileId(importId);m.setMatchResult("MATCH");m.setReferenceDate(LocalDate.of(2026,1,1));m.setCreatedAt(LocalDateTime.now());matches.insert(m);JobInterviewScore s=new JobInterviewScore();s.setExamYear(2026);s.setPositionCode("A001");s.setMinInterviewScore(new BigDecimal("132.6"));s.setInterviewCandidateCount(3);s.setSourceFileName("test.xls");s.setCreatedAt(LocalDateTime.now());s.setUpdatedAt(LocalDateTime.now());scores.upsert(s);}
 @Test void rebuildIsIdempotentAndRecommendationExcludesItsOwnScore()throws Exception{call(post("/api/job-features/rebuild").param("importId",importId.toString()));call(post("/api/job-features/rebuild").param("importId",importId.toString()));JsonNode feature=call(get("/api/job-features/"+positionId)).get("data");assertEquals("RECOGNIZED",feature.get("examSubjectStatus").asText());assertTrue(feature.get("examSubjectGroup").asText().contains("行政执法类"));JsonNode page=call(get("/api/recommendations").param("profileId",profileId.toString()).param("importId",importId.toString()).param("examYear","2026")).get("data");assertEquals(1,page.get("total").asInt());JsonNode item=page.get("items").get(0);assertEquals("A001",item.get("positionCode").asText());assertEquals("NORMAL",item.get("priorityLevel").asText());assertEquals(0,item.get("historicalAnalysis").get("sampleCount").asInt());assertEquals("LOW",item.get("historicalAnalysis").get("confidence").asText());assertFalse(item.get("historicalAnalysis").get("reliable").asBoolean());assertFalse(item.get("historicalAnalysis").get("rankingEligible").asBoolean());}
 @Test void preferenceCanBeSavedAndApplied()throws Exception{call(post("/api/job-features/rebuild").param("importId",importId.toString()));String body="{\"preferredRegions\":[\"南昌\"],\"acceptedOrgLevels\":[],\"excludedOrgLevels\":[],\"preferredSubjectGroups\":[],\"acceptExtraSubjects\":true,\"preferMoreRecruits\":true}";JsonNode saved=call(put("/api/preferences/"+profileId).contentType(MediaType.APPLICATION_JSON).content(body)).get("data");assertEquals("南昌",saved.get("preferredRegions").get(0).asText());JsonNode item=call(get("/api/recommendations").param("profileId",profileId.toString()).param("importId",importId.toString())).get("data").get("items").get(0);assertEquals("PRIORITY",item.get("priorityLevel").asText());assertEquals("地区符合偏好",item.get("recommendReasons").get(0).asText());}
 @Test void recommendationIsIsolatedByImportAndItsExamYear()throws Exception{call(post("/api/job-features/rebuild").param("importId",importId.toString()));ImportFile second=new ImportFile();second.setOriginalName("2025-jobs.xls");second.setStoredName("2025-jobs.xls");second.setStoredPath("target/2025-jobs.xls");second.setExamYear(2025);second.setStatus("IMPORTED");second.setCreatedAt(LocalDateTime.now().plusSeconds(1));imports.insert(second);JobPosition job=new JobPosition();job.setImportFileId(second.getId());job.setPositionCode("A001");job.setPositionName("同代码的2025岗位");job.setRecruitCount(2);job.setMajorRequirement("不限");job.setRawData("{\"科目数量\":\"考两科\",\"考试科目\":\"行政职业能力测验,申论（行政执法类）\"}");job.setCreatedAt(LocalDateTime.now());job.setUpdatedAt(LocalDateTime.now());positions.insertBatch(Collections.singletonList(job));JobMatch match=new JobMatch();match.setProfileId(profileId);match.setJobPositionId(job.getId());match.setImportFileId(second.getId());match.setMatchResult("MATCH");match.setReferenceDate(LocalDate.of(2025,1,1));match.setCreatedAt(LocalDateTime.now());matches.insert(match);JobInterviewScore score=new JobInterviewScore();score.setExamYear(2025);score.setPositionCode("A001");score.setMinInterviewScore(new BigDecimal("118.8"));score.setInterviewCandidateCount(2);score.setSourceFileName("2025-score.xls");score.setCreatedAt(LocalDateTime.now());score.setUpdatedAt(LocalDateTime.now());scores.upsert(score);call(post("/api/job-features/rebuild").param("importId",second.getId().toString()));JsonNode first=call(get("/api/recommendations").param("profileId",profileId.toString()).param("importId",importId.toString())).get("data");JsonNode other=call(get("/api/recommendations").param("profileId",profileId.toString()).param("importId",second.getId().toString())).get("data");assertEquals(1,first.get("total").asInt());assertEquals("行政执法岗",first.get("items").get(0).get("positionName").asText());assertEquals("132.6",first.get("items").get(0).get("minInterviewScore").asText());assertEquals(1,other.get("total").asInt());assertEquals("同代码的2025岗位",other.get("items").get(0).get("positionName").asText());assertEquals("118.8",other.get("items").get(0).get("minInterviewScore").asText());}
 private JsonNode call(org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder b)throws Exception{MvcResult r=mvc.perform(b).andExpect(status().isOk()).andReturn();JsonNode root=json.readTree(r.getResponse().getContentAsString(StandardCharsets.UTF_8));assertEquals(0,root.get("code").asInt(),root.toString());return root;}
}
