package com.gk.jobhelper.service;
import com.fasterxml.jackson.databind.ObjectMapper;import com.gk.jobhelper.dto.*;import com.gk.jobhelper.entity.*;import com.gk.jobhelper.mapper.*;import org.junit.jupiter.api.Test;import java.math.BigDecimal;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.mock;
class HistoricalAnalysisServiceTest {
 private final HistoricalAnalysisService service=new HistoricalAnalysisService(mock(JobPositionMapper.class),mock(JobPositionFeatureMapper.class),mock(JobInterviewScoreMapper.class),new ObjectMapper());
 @Test void singleSelfSampleMustRemainLow(){JobPosition p=position("A",1);JobPositionFeature f=feature("行测|申论（行政执法类）");JobInterviewScore s=score("A","132.6");HistoricalAnalysisVO v=service.analyze(p,f,s,Collections.singletonList(row("A","132.6",1,"行测|申论（行政执法类）")));assertEquals(1,v.getSampleCount());assertEquals("LOW",v.getConfidence());assertFalse(v.isReliable());assertEquals(50d,v.getPercentile());}
 @Test void tenExactComparableSamplesUseLevel1AndMidrank(){List<HistoricalSampleRow> rows=new ArrayList<>();for(int i=0;i<10;i++)rows.add(row("P"+i,String.valueOf(120+i),1,"G"));HistoricalAnalysisVO v=service.analyze(position("P5",1),feature("G"),score("P5","125"),rows);assertEquals("LEVEL1",v.getComparisonLevel());assertEquals(10,v.getSampleCount());assertEquals("MEDIUM",v.getConfidence());assertEquals(55d,v.getPercentile());assertTrue(v.isReliable());}
 @Test void differentSubjectGroupIsNeverCompared(){List<HistoricalSampleRow> rows=Arrays.asList(row("A","130",1,"G1"),row("B","100",1,"G2"));HistoricalAnalysisVO v=service.analyze(position("A",1),feature("G1"),score("A","130"),rows);assertEquals(1,v.getSampleCount());}
 @Test void comparableStatisticsWorkWithoutSamePositionCode(){List<HistoricalSampleRow> rows=new ArrayList<>();for(int i=0;i<10;i++){HistoricalSampleRow r=row("OLD"+i,String.valueOf(120+i),1,"G");r.setExamYear(i<5?2025:2026);rows.add(r);}HistoricalAnalysisVO v=service.analyze(position("NEW-CODE",1),feature("G"),null,rows,2027);assertTrue(v.isAvailable());assertEquals(10,v.getSampleCount());assertEquals(new BigDecimal("124.50"),v.getSampleAverageScore());assertEquals(new BigDecimal("124.50"),v.getSampleMedianScore());assertEquals(new BigDecimal("120"),v.getSampleMinScore());assertEquals(new BigDecimal("129"),v.getSampleMaxScore());assertNull(v.getPercentile());assertEquals("MEDIUM",v.getConfidence());}
 private JobPosition position(String c,int n){JobPosition p=new JobPosition();p.setPositionCode(c);p.setRecruitCount(n);return p;}private JobPositionFeature feature(String g){JobPositionFeature f=new JobPositionFeature();f.setExamSubjectGroup(g);f.setMajorRestrictionType("UNRESTRICTED");f.setMajorDomains("[]");return f;}private JobInterviewScore score(String c,String s){JobInterviewScore x=new JobInterviewScore();x.setExamYear(2026);x.setPositionCode(c);x.setMinInterviewScore(new BigDecimal(s));return x;}private HistoricalSampleRow row(String c,String s,int n,String g){HistoricalSampleRow r=new HistoricalSampleRow();r.setPositionCode(c);r.setMinInterviewScore(new BigDecimal(s));r.setRecruitCount(n);r.setExamSubjectGroup(g);r.setMajorRestrictionType("UNRESTRICTED");r.setMajorDomains("[]");return r;}
}
