package com.gk.jobhelper.service;
import com.gk.jobhelper.common.*;import com.gk.jobhelper.entity.RecruitmentPosition;import java.io.*;import java.time.*;import java.util.*;import org.apache.poi.ss.usermodel.*;import org.apache.poi.ss.util.CellRangeAddress;import org.springframework.stereotype.Component;
@Component public class ExcelRecruitmentPositionExtractor implements RecruitmentPositionExtractor {private final RecruitmentExcelHeaderNormalizer normalizer;public ExcelRecruitmentPositionExtractor(RecruitmentExcelHeaderNormalizer n){normalizer=n;}public boolean supports(String fileType){return "XLS".equals(fileType)||"XLSX".equals(fileType);}public RecruitmentPositionExtractionResult extract(DownloadedAttachment attachment,Long noticeId){try(Workbook book=WorkbookFactory.create(new ByteArrayInputStream(attachment.getBytes()))){List<RecruitmentPosition> all=new ArrayList<>();Map<String,Integer> headers=new LinkedHashMap<>();for(int i=0;i<book.getNumberOfSheets();i++){Sheet sheet=book.getSheetAt(i);int header=findHeader(sheet);if(header<0)continue;headers.put(sheet.getSheetName(),header+1);all.addAll(rows(sheet,header,noticeId,attachment.getAttachmentId()));}return new RecruitmentPositionExtractionResult(all,book.getNumberOfSheets(),headers);}catch(Exception e){String m=e.getMessage();throw new BusinessException(ApiResponse.CODE_BAD_REQUEST,"岗位表读取失败"+(m==null?"":"："+m));}}
 private int findHeader(Sheet s){for(int row=0;row<=Math.min(s.getLastRowNum(),60);row++){Map<Integer,String> values=rowValues(s,row);int recognized=0;boolean hasName=false;Set<String> fields=new HashSet<>();for(String value:values.values()){String field=normalizer.normalize(value);if(field!=null){fields.add(field);if("POSITION_NAME".equals(field))hasName=true;}}recognized=fields.size();if(hasName&&recognized>=3)return row;}return -1;}
 private List<RecruitmentPosition> rows(Sheet s,int header,Long noticeId,Long attachmentId){Map<Integer,String> columns=new LinkedHashMap<>();for(Map.Entry<Integer,String> e:rowValues(s,header).entrySet()){String f=normalizer.normalize(e.getValue());if(f!=null&&!columns.containsValue(f))columns.put(e.getKey(),f);}List<RecruitmentPosition> out=new ArrayList<>();for(int row=header+1;row<=s.getLastRowNum();row++){Map<Integer,String> values=rowValues(s,row);if(blank(values))continue;Map<String,String> data=new LinkedHashMap<>();for(Map.Entry<Integer,String> col:columns.entrySet())data.put(col.getValue(),trim(values.get(col.getKey())));String name=data.get("POSITION_NAME");if(skip(name,data))continue;RecruitmentPosition p=new RecruitmentPosition();p.setNoticeId(noticeId);p.setSourceAttachmentId(attachmentId);p.setPositionName(name);p.setPositionCode(data.get("POSITION_CODE"));p.setOrganizationName(data.get("ORGANIZATION"));p.setDepartmentName(data.get("DEPARTMENT"));p.setRecruitCount(number(data.get("RECRUIT_COUNT")));p.setWorkLocation(data.get("WORK_LOCATION"));p.setEducationRequirement(data.get("EDUCATION"));p.setDegreeRequirement(data.get("DEGREE"));p.setMajorRequirement(data.get("MAJOR"));p.setAgeRequirement(data.get("AGE"));p.setWorkYearsRequirement(data.get("WORK_EXPERIENCE"));p.setResponsibility(data.get("RESPONSIBILITY"));p.setOtherRequirement(data.get("REQUIREMENT"));p.setRawRequirement(raw(data));p.setSourceSheet(s.getSheetName());p.setSourceRow(row+1);p.setCreatedAt(LocalDateTime.now());p.setUpdatedAt(LocalDateTime.now());out.add(p);}return out;}
 private Map<Integer,String> rowValues(Sheet s,int row){Map<Integer,String> result=new LinkedHashMap<>();Row r=s.getRow(row);int max=r==null?0:Math.max(0,r.getLastCellNum());for(int col=0;col<max;col++)result.put(col,text(cell(s,row,col)));return result;}
 private Cell cell(Sheet s,int row,int col){Cell direct=s.getRow(row)==null?null:s.getRow(row).getCell(col);if(direct!=null&&text(direct).length()>0)return direct;for(int i=0;i<s.getNumMergedRegions();i++){CellRangeAddress range=s.getMergedRegion(i);if(range.isInRange(row,col))return s.getRow(range.getFirstRow())==null?null:s.getRow(range.getFirstRow()).getCell(range.getFirstColumn());}return direct;}
 private String text(Cell c){if(c==null)return "";try{return new DataFormatter().formatCellValue(c).trim();}catch(Exception e){return "";}}
 private boolean blank(Map<Integer,String> values){for(String v:values.values())if(!trim(v).isEmpty())return false;return true;}
 private boolean skip(String name,Map<String,String> data){String n=trim(name);if(n.isEmpty())return true;if(n.matches("^(合计|总计|备注|说明|注|注释|附件).*$"))return true;String raw=raw(data);return raw.matches("^(合计|总计|备注|说明|注|注释).*");}
 private String raw(Map<String,String> data){StringBuilder b=new StringBuilder();for(Map.Entry<String,String> e:data.entrySet())if(!trim(e.getValue()).isEmpty()){if(b.length()>0)b.append("；");b.append(e.getKey()).append("：").append(e.getValue());}return b.toString();}
 private Integer number(String text){try{String n=trim(text).replaceAll("[^0-9]","");return n.isEmpty()?null:Integer.valueOf(n);}catch(Exception e){return null;}}
 private String trim(String s){return s==null?"":s.trim();}}
