package com.gk.jobhelper.service;
import com.gk.jobhelper.dto.RecruitmentNoticeCandidate;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import java.util.regex.*;import org.jsoup.Jsoup;import org.jsoup.nodes.*;import org.springframework.stereotype.Component;
@Component public class JiangxiTalentEvaluationRecruitmentSource implements RecruitmentSource {
 private static final List<String> LIST_URLS=Arrays.asList("https://www.jxrcrsksta.com/list/7","https://www.jxrcrsksta.com/list/18");private static final Pattern CONTENT=Pattern.compile("/content/\\d+(?:\\?[^#\\s\\\"]*)?");private static final Pattern DATE=Pattern.compile("(20\\d{2}-\\d{2}-\\d{2})");
 public String getSourceCode(){return "JIANGXI_TALENT_EVALUATION";}public String getSourceName(){return "江西省人才测评中心";}
 public List<RecruitmentNoticeCandidate> fetchLatest(){List<RecruitmentNoticeCandidate> all=new ArrayList<>();Set<String> urls=new LinkedHashSet<>();for(String listUrl:LIST_URLS)for(RecruitmentNoticeCandidate candidate:fetch(listUrl))if(urls.add(candidate.getNoticeUrl()))all.add(candidate);return all;}
 private List<RecruitmentNoticeCandidate> fetch(String listUrl){try{HttpURLConnection c=(HttpURLConnection)new URL(listUrl).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(20000);c.setRequestProperty("User-Agent","Mozilla/5.0");if(c.getResponseCode()!=200)throw new IllegalStateException("招聘网站返回 HTTP "+c.getResponseCode());return parseDocument(Jsoup.parse(read(c.getInputStream()),listUrl),listUrl);}catch(IOException e){throw new IllegalStateException("访问江西省人才测评中心招聘网站失败: "+e.getMessage(),e);}}
 List<RecruitmentNoticeCandidate> parseDocument(Document doc){return parseDocument(doc,LIST_URLS.get(0));}
 private List<RecruitmentNoticeCandidate> parseDocument(Document doc,String listUrl){List<RecruitmentNoticeCandidate> out=new ArrayList<>();Set<String> urls=new LinkedHashSet<>();for(Element a:doc.select("a[href]")){String href=a.attr("href").trim(),title=a.text().trim();if(title.isEmpty()||!CONTENT.matcher(href).find())continue;String url=URI.create(listUrl).resolve(href).normalize().toString();if(!urls.add(url))continue;LocalDateTime published=date(a.parent()==null?"":a.parent().text());out.add(new RecruitmentNoticeCandidate(title,url,published));}if(out.isEmpty())throw new IllegalStateException("招聘列表页面结构异常，未识别到公告");return out;}
 private LocalDateTime date(String text){Matcher m=DATE.matcher(text);try{return m.find()?LocalDate.parse(m.group(1),DateTimeFormatter.ISO_LOCAL_DATE).atStartOfDay():null;}catch(Exception ignored){return null;}}
 private String read(InputStream in)throws IOException{try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){StringBuilder b=new StringBuilder();String s;while((s=r.readLine())!=null)b.append(s).append('\n');return b.toString();}}
}
