package com.gk.jobhelper.service;
import com.gk.jobhelper.dto.RecruitmentNoticeCandidate;import org.jsoup.Jsoup;import org.jsoup.nodes.Document;import org.springframework.stereotype.Component;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import java.util.regex.*;import java.util.stream.Collectors;
@Component public class JiangxiSasacRecruitmentSource implements RecruitmentSource {
 private static final String LIST_URL="https://gzw.jiangxi.gov.cn/jxsgzw/rczp/index.html";private static final Pattern ITEM=Pattern.compile("\\\"title\\\":\\\"(.*?)\\\".*?\\\"pubDate\\\":\\\"(.*?)\\\".*?\\\"urls\\\":\\\"\\{\\\\\\\"pc\\\\\\\":\\\\\\\"(.*?)\\\\\\\"",Pattern.DOTALL);private static final DateTimeFormatter DATE=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
 public String getSourceCode(){return "JIANGXI_SASAC";}public String getSourceName(){return "江西省国有资产监督管理委员会";}
 public List<RecruitmentNoticeCandidate> fetchLatest(){try{HttpURLConnection c=(HttpURLConnection)new URL(LIST_URL).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(20000);c.setRequestProperty("User-Agent","Mozilla/5.0");if(c.getResponseCode()!=200)throw new IllegalStateException("招聘网站返回 HTTP "+c.getResponseCode());String html=read(c.getInputStream());return parseDocument(Jsoup.parse(html,LIST_URL));}catch(IOException e){throw new IllegalStateException("访问江西省国资委招聘网站失败: "+e.getMessage(),e);}}
 List<RecruitmentNoticeCandidate> parseDocument(Document doc){String script=doc.select("script").stream().map(e->e.data()).collect(Collectors.joining("\n"));Matcher m=ITEM.matcher(script);List<RecruitmentNoticeCandidate> out=new ArrayList<>();Set<String> urls=new LinkedHashSet<>();while(m.find()){String title=Jsoup.parse(m.group(1).replace("\\\"","\"")).text().trim();String url=URI.create(LIST_URL).resolve(m.group(3).replace("\\/","/")).toString();LocalDateTime date=null;try{date=LocalDateTime.parse(m.group(2),DATE);}catch(Exception ignored){}if(!title.isEmpty()&&urls.add(url))out.add(new RecruitmentNoticeCandidate(title,url,date));}if(out.isEmpty())throw new IllegalStateException("招聘列表页面结构异常，未识别到公告");return out;}
 private String read(InputStream in)throws IOException{try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){StringBuilder b=new StringBuilder();String s;while((s=r.readLine())!=null)b.append(s).append('\n');return b.toString();}}
}
