package com.gk.jobhelper.service;
import com.gk.jobhelper.dto.RecruitmentNoticeVO;import java.io.*;import java.net.*;import java.time.*;import java.util.*;import org.jsoup.*;import org.jsoup.nodes.*;import org.jsoup.safety.Safelist;import org.slf4j.*;import org.springframework.stereotype.Component;
@Component public class JiangxiSasacRecruitmentDetailFetcher implements RecruitmentDetailFetcher {
 private static final Logger log=LoggerFactory.getLogger(JiangxiSasacRecruitmentDetailFetcher.class);private final RecruitmentAttachmentClassifier classifier;public JiangxiSasacRecruitmentDetailFetcher(RecruitmentAttachmentClassifier c){classifier=c;}
 public boolean supports(RecruitmentNoticeVO n){return "JIANGXI_SASAC".equals(n.getSourceCode());}
 public RecruitmentDetailFetchResult fetch(RecruitmentNoticeVO n){try{URLConnection raw=new URL(n.getNoticeUrl()).openConnection();if(!(raw instanceof HttpURLConnection))throw new IllegalStateException("公告地址无效");HttpURLConnection c=(HttpURLConnection)raw;c.setConnectTimeout(10000);c.setReadTimeout(20000);c.setInstanceFollowRedirects(true);c.setRequestProperty("User-Agent","Mozilla/5.0");c.setRequestProperty("Accept-Encoding","gzip");int status=c.getResponseCode();if(status!=200)throw new IllegalStateException("公告页面暂时无法访问，请稍后重试。");InputStream in="gzip".equalsIgnoreCase(c.getContentEncoding())?new java.util.zip.GZIPInputStream(c.getInputStream()):c.getInputStream();Document doc=Jsoup.parse(in,null,n.getNoticeUrl());log.info("江西国资委详情：status={}, finalUrl={}, contentType={}, charset={}, htmlLength={}, title={}, candidates={}",status,c.getURL(),c.getContentType(),doc.charset(),doc.outerHtml().length(),doc.title(),candidates(doc));Element content=findContent(doc);if(content==null||content.text().trim().isEmpty())throw new IllegalStateException("公告正文暂时无法识别，请稍后重试。");List<RecruitmentAttachmentDraft> files=attachments(content,n.getNoticeUrl());content.select("script,style,iframe,object,embed,form,nav,footer").remove();String html=Jsoup.clean(content.html(),n.getNoticeUrl(),Safelist.relaxed());String text=Jsoup.parse(html).text().trim();if(text.isEmpty())throw new IllegalStateException("公告正文为空，请稍后重试。");return new RecruitmentDetailFetchResult(doc.title(),null,html,text,files);}catch(IllegalStateException e){throw e;}catch(Exception e){log.warn("江西国资委公告详情访问失败，url={}, type={}, message={}",n.getNoticeUrl(),e.getClass().getSimpleName(),e.getMessage());throw new IllegalStateException("公告页面暂时无法访问，请稍后重试。",e);}}
 Element findContent(Document d){for(String selector:new String[]{".xlcon.xl-nr","#zoom",".TRS_Editor",".article-content",".articleContent",".detail-content",".con",".content","article","main"}){Element e=d.selectFirst(selector);if(e!=null&&e.text().trim().length()>20)return e;}Element best=null;for(Element e:d.select("div,section,td")){String text=e.text().trim();if(text.length()>120&&(best==null||text.length()>best.text().trim().length()))best=e;}return best;}
 private String candidates(Document d){List<String> values=new ArrayList<>();for(Element e:d.select("div,section,article").subList(0,Math.min(20,d.select("div,section,article").size())))values.add(e.tagName()+"#"+e.id()+"."+e.className()+":"+Math.min(80,e.text().length()));return values.toString();}
 private List<RecruitmentAttachmentDraft> attachments(Element content,String base){Map<String,RecruitmentAttachmentDraft> out=new LinkedHashMap<>();for(Element a:content.select("a[href]")){String href=a.attr("href").trim(),text=a.text().trim();if(href.isEmpty()||href.startsWith("javascript:")||href.startsWith("#"))continue;try{String url=URI.create(base).resolve(href).normalize().toString();String pathName=fileName(url),category=classifier.attachmentType(text),type=classifier.fileType(pathName);if(!isAttachmentCandidate(text,url,type,category))continue;String name="OTHER".equals(type)&&!text.isEmpty()?text:pathName;if(name.isEmpty())name=text;out.putIfAbsent(url+"\n"+name,new RecruitmentAttachmentDraft(name,url,type,category,text));}catch(IllegalArgumentException ignored){}}return new ArrayList<>(out.values());}
 private boolean isAttachmentCandidate(String text,String url,String type,String category){if(!"OTHER".equals(category)||!"OTHER".equals(type))return true;String value=(text+" "+url).toLowerCase(Locale.ROOT);return value.contains("附件")||value.contains("download")||value.contains("file")||value.contains("attachment")||value.contains("upload")||value.contains("resource");}
 private String fileName(String url){try{String path=URI.create(url).getPath();String n=path.substring(path.lastIndexOf('/')+1);return URLDecoder.decode(n,"UTF-8");}catch(Exception e){return "";}}
}
