package com.gk.jobhelper.service;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import com.gk.jobhelper.common.BusinessException;import com.gk.jobhelper.dto.JobPreferenceRequest;import com.gk.jobhelper.entity.JobPreference;import com.gk.jobhelper.mapper.*;import org.springframework.stereotype.Service;
import java.time.LocalDateTime;import java.util.*;
@Service public class JobPreferenceService {
 private final JobPreferenceMapper mapper;private final UserProfileMapper profileMapper;private final ObjectMapper json;
 public JobPreferenceService(JobPreferenceMapper m,UserProfileMapper p,ObjectMapper j){mapper=m;profileMapper=p;json=j;}
 public JobPreferenceRequest get(Long profileId){require(profileId);JobPreference p=mapper.selectByProfileId(profileId);if(p==null)return new JobPreferenceRequest();JobPreferenceRequest r=new JobPreferenceRequest();r.setPreferredRegions(list(p.getPreferredRegions()));r.setAcceptedOrgLevels(list(p.getAcceptedOrgLevels()));r.setExcludedOrgLevels(list(p.getExcludedOrgLevels()));r.setPreferredSubjectGroups(list(p.getPreferredSubjectGroups()));r.setAcceptExtraSubjects(p.getAcceptExtraSubjects());r.setPreferMoreRecruits(p.getPreferMoreRecruits());return r;}
 public JobPreferenceRequest save(Long profileId,JobPreferenceRequest r){require(profileId);if(r==null)r=new JobPreferenceRequest();JobPreference p=new JobPreference();p.setProfileId(profileId);p.setPreferredRegions(write(r.getPreferredRegions()));p.setAcceptedOrgLevels(write(r.getAcceptedOrgLevels()));p.setExcludedOrgLevels(write(r.getExcludedOrgLevels()));p.setPreferredSubjectGroups(write(r.getPreferredSubjectGroups()));p.setAcceptExtraSubjects(!Boolean.FALSE.equals(r.getAcceptExtraSubjects()));p.setPreferMoreRecruits(!Boolean.FALSE.equals(r.getPreferMoreRecruits()));p.setCreatedAt(LocalDateTime.now());p.setUpdatedAt(LocalDateTime.now());mapper.upsert(p);return get(profileId);}
 private void require(Long id){if(id==null||profileMapper.selectById(id)==null)throw new BusinessException("档案不存在: "+id);}private String write(Object v){try{return json.writeValueAsString(v==null?Collections.emptyList():v);}catch(Exception e){return "[]";}}private List<String> list(String v){try{return json.readValue(v,new TypeReference<List<String>>(){});}catch(Exception e){return new ArrayList<>();}}
}
