package com.gk.jobhelper.service;

import com.gk.jobhelper.dto.*;import com.gk.jobhelper.entity.*;import com.gk.jobhelper.mapper.*;import org.springframework.stereotype.Service;
import java.util.*;import java.util.function.Function;import java.util.stream.Collectors;

@Service
public class RecommendationService {
 private final RecommendationMapper recommendationMapper;private final JobPositionFeatureMapper featureMapper;private final JobInterviewScoreMapper scoreMapper;private final JobFavoriteMapper favoriteMapper;private final JobPreferenceService preferenceService;private final JobFeatureService featureService;private final HistoricalAnalysisService historicalService;private final JobRegionResolver regionResolver;private final ImportContextService importContextService;
 public RecommendationService(RecommendationMapper r,JobPositionFeatureMapper f,JobInterviewScoreMapper s,JobFavoriteMapper fav,JobPreferenceService p,JobFeatureService fs,HistoricalAnalysisService hs,JobRegionResolver rr,ImportContextService context){recommendationMapper=r;featureMapper=f;scoreMapper=s;favoriteMapper=fav;preferenceService=p;featureService=fs;historicalService=hs;regionResolver=rr;importContextService=context;}
 public PageVO<RecommendationItemVO> page(Long profileId,Long importId,String priority,int page,int size){int year=importContextService.requireExamYear(importId);JobPreferenceRequest pref=preferenceService.get(profileId);List<RecommendationCandidateRow> candidates=recommendationMapper.selectMatchCandidates(profileId,importId);if(candidates.isEmpty())return new PageVO<>(0,Math.max(1,page),Math.max(1,size),new ArrayList<>());
  List<Long> ids=candidates.stream().map(RecommendationCandidateRow::getPositionId).collect(Collectors.toList());Map<Long,JobPositionFeature> features=featureMapper.selectByPositionIds(ids).stream().collect(Collectors.toMap(JobPositionFeature::getPositionId,Function.identity()));
  List<String> codes=candidates.stream().map(RecommendationCandidateRow::getPositionCode).filter(Objects::nonNull).distinct().collect(Collectors.toList());Map<String,JobInterviewScore> scores=codes.isEmpty()?new HashMap<>():scoreMapper.selectByYearAndCodes(year,codes).stream().collect(Collectors.toMap(JobInterviewScore::getPositionCode,Function.identity(),(a,b)->a));
  Set<Long> favorites=new HashSet<>(favoriteMapper.selectPositionIds(profileId,ids));List<HistoricalSampleRow> samples=scoreMapper.selectAnalysisSamples();List<RecommendationItemVO> all=new ArrayList<>();
  for(RecommendationCandidateRow c:candidates){JobPositionFeature f=features.get(c.getPositionId());JobInterviewScore score=scores.get(c.getPositionCode());HistoricalAnalysisVO analysis=historicalService.analyze(position(c),f,score,samples,year);RecommendationItemVO item=build(c,f,score,analysis,favorites.contains(c.getPositionId()),pref);if(priority==null||priority.trim().isEmpty()||priority.equals(item.getPriorityLevel()))all.add(item);}
  all.sort(Comparator.comparingInt((RecommendationItemVO v)->rank(v.getPriorityLevel())).thenComparing(v->v.getHistoricalAnalysis()!=null&&v.getHistoricalAnalysis().isRankingEligible()?v.getHistoricalAnalysis().getPercentile():999d).thenComparing((RecommendationItemVO v)->v.getRecruitCount()==null?0:-v.getRecruitCount()).thenComparing(v->v.getPositionCode()==null?"":v.getPositionCode()));
  int safePage=Math.max(1,page),safeSize=Math.min(100,Math.max(1,size)),from=Math.min(all.size(),(safePage-1)*safeSize),to=Math.min(all.size(),from+safeSize);return new PageVO<>(all.size(),safePage,safeSize,new ArrayList<>(all.subList(from,to)));
 }
 private RecommendationItemVO build(RecommendationCandidateRow c,JobPositionFeature f,JobInterviewScore score,HistoricalAnalysisVO h,boolean favorite,JobPreferenceRequest pref){RecommendationItemVO v=new RecommendationItemVO();v.setPositionId(c.getPositionId());v.setPositionCode(c.getPositionCode());v.setPositionName(c.getPositionName());v.setDepartmentName(c.getDepartmentName());v.setOrganizationName(c.getOrganizationName());v.setRegion(regionResolver.resolve(c));v.setRecruitCount(c.getRecruitCount());v.setEducationRequirement(c.getEducationRequirement());v.setMajorRequirement(c.getMajorRequirement());v.setFavorite(favorite);v.setHistoricalAnalysis(h);if(score!=null)v.setMinInterviewScore(score.getMinInterviewScore());if(f!=null){JobFeatureVO fv=featureService.toVO(f);v.setExamSubjectCount(fv.getExamSubjectCount());v.setExamSubjects(fv.getExamSubjects());v.setExamSubjectGroup(fv.getExamSubjectGroup());v.setMajorRestrictionType(fv.getMajorRestrictionType());}
  int points=0;boolean forcedOther=false;List<String> reasons=new ArrayList<>();if(regionResolver.matches(pref.getPreferredRegions(),c)){points+=3;reasons.add("地区符合偏好");}if(f!=null&&pref.getPreferredSubjectGroups().contains(f.getExamSubjectGroup())){points+=3;reasons.add("考试科目符合偏好");}else if(Boolean.FALSE.equals(pref.getAcceptExtraSubjects())&&!pref.getPreferredSubjectGroups().isEmpty())forcedOther=true;
  if(f!=null&&pref.getExcludedOrgLevels().contains(f.getOrganizationLevel()))forcedOther=true;if(f!=null&&!pref.getAcceptedOrgLevels().isEmpty()&&!pref.getAcceptedOrgLevels().contains(f.getOrganizationLevel()))forcedOther=true;
  if(Boolean.TRUE.equals(pref.getPreferMoreRecruits())&&c.getRecruitCount()!=null&&c.getRecruitCount()>=3){points++;reasons.add("招录人数较多");}if(h!=null&&h.isRankingEligible()&&h.getPercentile()!=null){if(h.getPercentile()<25){points+=2;reasons.add("同类进面位置较低");}else if(h.getPercentile()<50){points++;reasons.add("同类进面位置中低");}}
  if(reasons.isEmpty())reasons.add("资格匹配结果为可以报");v.setRecommendReasons(reasons);v.setPriorityLevel(forcedOther?"OTHER":points>=3?"PRIORITY":"NORMAL");return v;}
 private boolean contains(List<String> prefs,String value){if(value==null)return false;for(String p:prefs)if(p!=null&&!p.trim().isEmpty()&&(value.contains(p.trim())||p.contains(value)))return true;return false;}
 private int rank(String p){return "PRIORITY".equals(p)?0:"NORMAL".equals(p)?1:2;}
 private JobPosition position(RecommendationCandidateRow c){JobPosition p=new JobPosition();p.setId(c.getPositionId());p.setPositionCode(c.getPositionCode());p.setRecruitCount(c.getRecruitCount());return p;}
}
