package com.gk.jobhelper.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.gk.jobhelper.common.ApiResponse;
import com.gk.jobhelper.common.BusinessException;
import com.gk.jobhelper.common.TextNormalizer;
import com.gk.jobhelper.constant.MatchResult;
import com.gk.jobhelper.dto.*;
import com.gk.jobhelper.entity.*;
import com.gk.jobhelper.mapper.*;
import com.gk.jobhelper.matcher.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.*;
import java.util.regex.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** 招聘岗位资格匹配：只回答能否报考，不包含推荐或评分。 */
@Service public class RecruitmentQualificationMatchService {
 private static final Pattern YEARS=Pattern.compile("(\\d+)\\s*年(?:及以上|以上|工作经验|工作经历|经验)?");
 private final UserProfileMapper profiles; private final CareerProfileMapper careers; private final RecruitmentPositionMapper positions; private final RecruitmentMatchMapper matches; private final EducationMatcher education; private final AgeMatcher age; private final MajorMatcher major; private final ObjectMapper json;
 public RecruitmentQualificationMatchService(UserProfileMapper p,CareerProfileMapper c,RecruitmentPositionMapper rp,RecruitmentMatchMapper rm,EducationMatcher e,AgeMatcher a,MajorMatcher m,ObjectMapper j){profiles=p;careers=c;positions=rp;matches=rm;education=e;age=a;major=m;json=j;}
 @Transactional public RecruitmentMatchResultVO match(Long positionId){UserProfile profile=requireProfile();RecruitmentPositionVO position=requirePosition(positionId);List<RecruitmentRequirement> requirements=positions.selectRequirementsByPositionId(positionId);List<RecruitmentMatchItem> items=buildItems(profile,position,requirements);RecruitmentMatchResult entity=aggregate(profile.getId(),positionId,items);LocalDateTime now=LocalDateTime.now();entity.setCreatedAt(now);entity.setUpdatedAt(now);matches.upsert(entity);RecruitmentMatchResult saved=matches.selectByProfileAndPosition(profile.getId(),positionId);matches.deleteItems(saved.getId());for(RecruitmentMatchItem item:items){item.setMatchResultId(saved.getId());item.setCreatedAt(now);}if(!items.isEmpty())matches.insertItems(items);return detail(saved);}
 @Transactional public List<RecruitmentMatchResultVO> matchNotice(Long noticeId){List<RecruitmentPositionVO> rows=positions.selectByNoticeId(noticeId);List<RecruitmentMatchResultVO> result=new ArrayList<>();for(RecruitmentPositionVO row:rows)result.add(match(row.getId()));return result;}
 @Transactional public Map<String,Long> rebuild(){Map<String,Long> counts=new LinkedHashMap<>();for(MatchResult r:MatchResult.values())counts.put(r.name(),0L);for(int offset=0;;offset+=100){List<Long> ids=positions.selectIds(offset,100);if(ids.isEmpty())break;for(Long id:ids){RecruitmentMatchResultVO value=match(id);counts.put(value.getResult(),counts.get(value.getResult())+1);}if(ids.size()<100)break;}return counts;}
 public RecruitmentMatchResultVO detail(Long positionId){UserProfile profile=requireProfile();RecruitmentMatchResult result=matches.selectByProfileAndPosition(profile.getId(),positionId);return result==null?null:detail(result);}
 private RecruitmentMatchResultVO detail(RecruitmentMatchResult source){RecruitmentMatchResultVO vo=new RecruitmentMatchResultVO();copy(source,vo);vo.setItems(matches.selectItems(source.getId()));return vo;}
 private void copy(RecruitmentMatchResult s,RecruitmentMatchResult t){t.setId(s.getId());t.setProfileId(s.getProfileId());t.setPositionId(s.getPositionId());t.setResult(s.getResult());t.setSummary(s.getSummary());t.setMatchedCount(s.getMatchedCount());t.setUncertainCount(s.getUncertainCount());t.setNotMatchedCount(s.getNotMatchedCount());t.setCreatedAt(s.getCreatedAt());t.setUpdatedAt(s.getUpdatedAt());}
 private RecruitmentMatchResult aggregate(Long profileId,Long positionId,List<RecruitmentMatchItem> items){int yes=0,uncertain=0,no=0;for(RecruitmentMatchItem item:items){if("PREFERRED".equals(item.getRequirementLevel()))continue;if("NOT_MATCH".equals(item.getResult()))no++;else if("UNCERTAIN".equals(item.getResult()))uncertain++;else yes++;}RecruitmentMatchResult r=new RecruitmentMatchResult();r.setProfileId(profileId);r.setPositionId(positionId);r.setMatchedCount(yes);r.setUncertainCount(uncertain);r.setNotMatchedCount(no);r.setResult(no>0?"NOT_MATCH":uncertain>0?"UNCERTAIN":"MATCH");r.setSummary("NOT_MATCH".equals(r.getResult())?"存在明确不满足的必要条件。":"UNCERTAIN".equals(r.getResult())?"必要条件中存在暂时无法确认的信息。":"所有已识别必要条件均明确满足。");return r;}
 private List<RecruitmentMatchItem> buildItems(UserProfile profile,RecruitmentPositionVO p,List<RecruitmentRequirement> requirements){Map<String,RecruitmentRequirement> byType=new LinkedHashMap<>();for(RecruitmentRequirement r:requirements)byType.putIfAbsent(r.getRequirementType(),r);List<RecruitmentMatchItem> out=new ArrayList<>();add(out,byType.get("EDUCATION"),"EDUCATION",p.getEducationRequirement(),evaluateEducation(profile,p));add(out,byType.get("DEGREE"),"DEGREE",p.getDegreeRequirement(),evaluateDegree(profile,p.getDegreeRequirement()));add(out,byType.get("MAJOR"),"MAJOR",p.getMajorRequirement(),evaluateMajor(profile,p));add(out,byType.get("AGE"),"AGE",p.getAgeRequirement(),evaluateAge(profile,p));add(out,byType.get("WORK_EXPERIENCE"),"WORK_EXPERIENCE",p.getWorkYearsRequirement(),evaluateWork(profile,p.getWorkYearsRequirement()));String other=p.getOtherRequirement();if(!TextNormalizer.isBlank(other))add(out,byType.get("OTHER"),"OTHER",other,evaluateOther(profile,other));return out;}
 private void add(List<RecruitmentMatchItem> out,RecruitmentRequirement req,String type,String raw,Eval v){if(TextNormalizer.isBlank(raw))return;RecruitmentMatchItem i=new RecruitmentMatchItem();i.setRequirementId(req==null?null:req.getId());i.setRequirementType(type);i.setRequirementLevel(req==null||req.getRequirementLevel()==null?"REQUIRED":req.getRequirementLevel());i.setResult(v.result.name());i.setPositionRequirement(raw);i.setUserEvidence(v.user);i.setReason(v.reason);out.add(i);}
 private Eval evaluateEducation(UserProfile profile,RecruitmentPositionVO p){JobPosition temp=new JobPosition();temp.setEducationRequirement(p.getEducationRequirement());MatchItemResult r=education.match(profile,temp,MatchContext.of(LocalDate.now()));return eval(r);}
 private Eval evaluateMajor(UserProfile profile,RecruitmentPositionVO p){JobPosition temp=new JobPosition();temp.setMajorRequirement(p.getMajorRequirement());MatchItemResult r=major.match(profile,temp,MatchContext.of(LocalDate.now()));return eval(r);}
 private Eval evaluateAge(UserProfile profile,RecruitmentPositionVO p){JobPosition temp=new JobPosition();temp.setAgeRequirement(p.getAgeRequirement());MatchItemResult r=age.match(profile,temp,MatchContext.of(LocalDate.now()));return eval(r);}
 private Eval evaluateDegree(UserProfile profile,String raw){String requirement=TextNormalizer.normalize(raw),user=TextNormalizer.normalize(profile.getDegree());if(requirement.isEmpty()||TextNormalizer.isUnlimited(requirement))return new Eval(MatchResult.MATCH,profile.getDegree(),"岗位未设置学位限制。");if(user.isEmpty())return new Eval(MatchResult.UNCERTAIN,null,"职业档案未提供学位信息，不能由学历自动推断学位。");Integer need=degreeLevel(requirement),actual=degreeLevel(user);if(need==null||actual==null)return new Eval(MatchResult.UNCERTAIN,profile.getDegree(),"无法可靠识别岗位或用户学位信息，需人工确认。");boolean exact=requirement.contains("仅限")||(!requirement.contains("及以上")&&!requirement.contains("以上"));boolean ok=exact?actual.equals(need):actual>=need;return new Eval(ok?MatchResult.MATCH:MatchResult.NOT_MATCH,profile.getDegree(),ok?"用户学位满足岗位要求。":"用户学位不满足岗位要求。");}
 private Integer degreeLevel(String value){if(value.contains("博士"))return 3;if(value.contains("硕士"))return 2;if(value.contains("学士"))return 1;return null;}
 private Eval evaluateWork(UserProfile profile,String raw){String requirement=TextNormalizer.normalize(raw);if(requirement.isEmpty()||TextNormalizer.isUnlimited(requirement))return new Eval(MatchResult.MATCH,null,"岗位未设置工作经验限制。");Matcher matcher=YEARS.matcher(requirement);if(!matcher.find())return new Eval(MatchResult.UNCERTAIN,null,"无法稳定识别工作经验年限，需人工确认。");int need=Integer.parseInt(matcher.group(1));if(requirement.contains("相关")||requirement.matches(".*(?:Java|金融|证券|支付|行业|系统).*"))return new Eval(MatchResult.UNCERTAIN,null,"岗位要求特定相关工作经验，职业画像缺少可确定的逐段行业/职责证据。");DurationResult duration=workDuration(profile.getId());if(duration.uncertain)return new Eval(MatchResult.UNCERTAIN,duration.display,"工作经历日期精度不足，无法可靠计算年限。");if(duration.days<need*365L)return new Eval(MatchResult.NOT_MATCH,duration.display,"可确定的非重叠工作经历不足"+need+"年。");return new Eval(MatchResult.MATCH,duration.display,"根据职业画像的非重叠工作经历计算，满足"+need+"年要求。");}
 private Eval evaluateOther(UserProfile p,String raw){String requirement=TextNormalizer.normalize(raw);if(requirement.contains("证")||requirement.contains("资格")){String evidence=p.getCertificates();if(TextNormalizer.isBlank(evidence))return new Eval(MatchResult.UNCERTAIN,null,"职业画像未提供相关证书或资格信息。");for(String item:evidence.split("[,，、;；]"))if(!item.trim().isEmpty()&&requirement.contains(item.trim()))return new Eval(MatchResult.MATCH,evidence,"职业画像记录了岗位要求的证书/资格。");return new Eval(MatchResult.UNCERTAIN,evidence,"已有证书记录无法与岗位证书要求可靠对应，需人工确认。");}return new Eval(MatchResult.UNCERTAIN,null,"该必要条件属于主观或复合要求，V1不做推断。");}
 private DurationResult workDuration(Long profileId){CareerProfile c=careers.selectByProfileId(profileId);if(c==null||TextNormalizer.isBlank(c.getWorkExperiences()))return new DurationResult(0,true,null);try{List<CareerWorkVO> works=json.readValue(c.getWorkExperiences(),new TypeReference<List<CareerWorkVO>>(){});List<LocalDate[]> spans=new ArrayList<>();for(CareerWorkVO w:works){LocalDate start=date(w.getStartDate(),false),end=date(w.getEndDate(),true);if(start==null||end==null)return new DurationResult(0,true,null);if(end.isBefore(start))return new DurationResult(0,true,null);spans.add(new LocalDate[]{start,end});}spans.sort(Comparator.comparing(a->a[0]));long days=0;LocalDate start=null,end=null;for(LocalDate[] span:spans){if(start==null){start=span[0];end=span[1];}else if(!span[0].isAfter(end.plusDays(1))){if(span[1].isAfter(end))end=span[1];}else{days+=Duration.between(start.atStartOfDay(),end.plusDays(1).atStartOfDay()).toDays();start=span[0];end=span[1];}}if(start!=null)days+=Duration.between(start.atStartOfDay(),end.plusDays(1).atStartOfDay()).toDays();return new DurationResult(days,false,String.format("%.1f年",days/365d));}catch(Exception e){return new DurationResult(0,true,null);}}
 private LocalDate date(String value,boolean end){if(value==null||value.trim().isEmpty()||"至今".equals(value.trim()))return end?LocalDate.now():null;String v=value.trim();try{if(v.matches("\\d{4}-\\d{2}-\\d{2}"))return LocalDate.parse(v);if(v.matches("\\d{4}-\\d{2}"))return YearMonth.parse(v).atEndOfMonth();}catch(DateTimeParseException ignored){}return null;}
 private Eval eval(MatchItemResult item){return new Eval(item.getResult(),item.getUserValue(),item.getReason());}
 private UserProfile requireProfile(){UserProfile p=profiles.selectFirstProfile();if(p==null)throw new BusinessException(ApiResponse.CODE_PROFILE_NOT_FOUND,"请先保存我的档案。");return p;}
 private RecruitmentPositionVO requirePosition(Long id){RecruitmentPositionVO p=positions.selectById(id);if(p==null)throw new BusinessException(ApiResponse.CODE_BAD_REQUEST,"招聘岗位不存在: "+id);return p;}
 private static class Eval{final MatchResult result;final String user,reason;Eval(MatchResult r,String u,String reason){result=r;user=u;this.reason=reason;}}
 private static class DurationResult{final long days;final boolean uncertain;final String display;DurationResult(long d,boolean u,String s){days=d;uncertain=u;display=s;}}
}
