package com.gk.jobhelper.service;
import com.gk.jobhelper.dto.*;import com.gk.jobhelper.entity.*;import com.gk.jobhelper.mapper.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import java.time.LocalDateTime;import java.util.*;
@Service public class RecruitmentDiscoveryService {
 private final RecruitmentSourceMapper sourceMapper;private final RecruitmentNoticeMapper noticeMapper;private final Map<String,RecruitmentSource> sources=new HashMap<>();
 public RecruitmentDiscoveryService(RecruitmentSourceMapper sm,RecruitmentNoticeMapper nm,List<RecruitmentSource> all){sourceMapper=sm;noticeMapper=nm;for(RecruitmentSource s:all)sources.put(s.getSourceCode(),s);}
 public RecruitmentDiscoveryResult discoverAll(){RecruitmentDiscoveryResult all=new RecruitmentDiscoveryResult();for(com.gk.jobhelper.entity.RecruitmentSource source:sourceMapper.selectEnabled())all.merge(discover(source));return all;}
 private RecruitmentDiscoveryResult discover(com.gk.jobhelper.entity.RecruitmentSource source){RecruitmentDiscoveryResult result=new RecruitmentDiscoveryResult();LocalDateTime now=LocalDateTime.now();RecruitmentSource adapter=sources.get(source.getSourceCode());if(adapter==null){result.setFailedCount(1);sourceMapper.updateFetch(source.getId(),now,"FAILED: 未配置来源实现");return result;}try{List<RecruitmentNoticeCandidate> candidates=adapter.fetchLatest();result.setFetchedCount(candidates.size());Set<String> seen=new HashSet<>();for(RecruitmentNoticeCandidate c:candidates){if(c.getTitle()==null||c.getTitle().trim().isEmpty()||c.getNoticeUrl()==null||c.getNoticeUrl().trim().isEmpty()||!seen.add(c.getNoticeUrl())){result.setFailedCount(result.getFailedCount()+1);continue;}if(noticeMapper.selectBySourceAndUrl(source.getId(),c.getNoticeUrl())!=null){result.setDuplicateCount(result.getDuplicateCount()+1);continue;}RecruitmentNotice n=new RecruitmentNotice();n.setSourceId(source.getId());n.setTitle(c.getTitle().trim());n.setNoticeUrl(c.getNoticeUrl());n.setPublishDate(c.getPublishDate());n.setNoticeType("RECRUITMENT");n.setUserStatus("NEW");n.setDiscoveredAt(now);n.setCreatedAt(now);n.setUpdatedAt(now);try{noticeMapper.insert(n);result.setNewCount(result.getNewCount()+1);}catch(DuplicateKeyException e){result.setDuplicateCount(result.getDuplicateCount()+1);}}sourceMapper.updateFetch(source.getId(),now,"SUCCESS");}catch(Exception e){result.setFailedCount(result.getFailedCount()+1);sourceMapper.updateFetch(source.getId(),now,"FAILED: "+trim(e.getMessage()));}return result;}
 private String trim(String value){return value==null?"未知错误":value.length()>200?value.substring(0,200):value;}
}
